# Generated by Django 3.0.7 on 2020-06-29 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200629_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
