# Generated by Django 3.0.7 on 2020-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_article_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_poster',
            field=models.ImageField(upload_to='poster_image'),
        ),
    ]
