# Generated by Django 3.0.7 on 2020-06-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200630_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_dislike',
            field=models.IntegerField(default=0, verbose_name='дизлайк'),
        ),
        migrations.AddField(
            model_name='article',
            name='count_like',
            field=models.IntegerField(default=0, verbose_name='лайк'),
        ),
    ]
