# Generated by Django 3.0.7 on 2020-06-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200701_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='count_dislike',
        ),
        migrations.RemoveField(
            model_name='article',
            name='count_like',
        ),
    ]
