# Generated by Django 3.0.7 on 2020-07-01 08:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_likes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
