# Generated by Django 3.0.7 on 2020-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20200701_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_poster',
            field=models.ImageField(upload_to='poster_image/%Y/%m/%d/'),
        ),
    ]
