# Generated by Django 3.0.7 on 2020-06-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/user_avatar/none/default_avatar.png', upload_to='user_avatar'),
        ),
    ]
