# Generated by Django 3.0.7 on 2020-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200630_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_choice',
            field=models.CharField(blank=True, choices=[('M', 'мужской'), ('W', 'женский'), ('ANOTHER', 'другой'), (None, 'не выбран')], default=None, max_length=7),
        ),
    ]
