# Generated by Django 3.0.7 on 2020-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200630_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_choice',
            field=models.CharField(blank=True, choices=[('M', 'мужской'), ('W', 'женский'), ('ANOTHER', 'другой'), (None, 'не выбран')], max_length=7),
        ),
    ]
