# Generated by Django 3.0.7 on 2020-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200702_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/avatar.png', upload_to='user_avatar/%Y/%m/%d/'),
        ),
    ]
